ERPSolutions_EF/Controllers/ButtonController.cs
using System.Web.Mvc;
using ERPSolutions_EF.Models;

namespace ERPSolutions_EF.Controllers
{
    public class ButtonController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Initiate()
        {
            return PartialView("Initiate");
        }

        public ActionResult Approve()
        {
            var employee = Employee.GetEmployee(User.Identity.Name);
            if (employee.HasRole((int)Enums.Roles.APPROVER) ||
                employee.HasRole((int)Enums.Roles.ADMINISTRATOR))
            {
                return PartialView("Approve");
            }

            return new EmptyResult();
        }

        public ActionResult Perform()
        {
            var employee = Employee.GetEmployee(User.Identity.Name);
            if (employee.HasRole((int)Enums.Roles.PERFORMER) ||
                employee.HasRole((int)Enums.Roles.ADMINISTRATOR))
            {
                return PartialView("Perform");
            }

            return new EmptyResult();
        }

        public ActionResult Report()
        {
            return PartialView("Report");
        }

        public ActionResult Settings()
        {
            var employee = Employee.GetEmployee(User.Identity.Name);
            if (employee.HasRole((int)Enums.Roles.ADMINISTRATOR))
            {
                return PartialView("Settings");
            }

            return new EmptyResult();
        }
    }
}

ERPSolutions_EF/Views/Shared/Block.cshtml
@{
    ViewBag.Title = "Доступ ограничен";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="col-md-12 text-center">
    <h2 class="alert-danger" style="padding: 50pt 0pt 50pt 0pt;">Доступ ограничен, требуется согласование ДИС</h2>
</div>

ERPSolutions_EF/Views/Shared/Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <link type="text/css" rel="stylesheet" href="@Url.Content("~/Styles/bootstrap.css")">
    <link type="text/css" rel="stylesheet" href="@Url.Content("~/Styles/bootstrap-theme.css")">
    <link type="text/css" rel="stylesheet" href="@Url.Content("~/Styles/Style.css")">
    <title>Журнал установок решений: @ViewBag.Title</title>
</head>
<body>
    <div class="col-md-12 col-sm-12 col-lg-12" style="margin-top: 20px;">
        <div class="text-left col-sm-4 col-md-4 col-lg-4" >
            <a href="@Url.Action("Index", "Home")"><img src="@Url.Content("~/logo.png")" width="250" /></a>
        </div>
        <div class="text-right col-md-8 col-sm-8 col-lg-8">
            <div class="h3" style="font-weight: bold;">Журнал установок решений</div>
        </div>
    </div>

    <div class="col-sm-12 col-md-12 col-lg-12" style="padding-top: 10pt;">
        <div class="col-sm-12 col-md-12 col-lg-12 text-right">
            @{Html.RenderAction("Initiate", "Button");}
            @{Html.RenderAction("Approve", "Button");}
            @{Html.RenderAction("Perform", "Button");}
            @{Html.RenderAction("Report", "Button");}
            @{Html.RenderAction("Settings", "Button");}
        </div>
        <div class="text-left col-sm-12 col-md-12 col-lg-12" style="margin-top: 20px;">
            @RenderBody()
        </div>
    </div>

    <div class="col-md-12 col-sm-12 col-lg-12 text-right">
        <div style="margin-right: 50px; padding-bottom: 50px; padding-top: 50px;">
            <small>
                Диспетчер ИТ
                <span class="glyphicon glyphicon-envelope text-info"></span>
                <a href="mailto:sd@domain.ru">sd@domain.ru</a>
                <span class="glyphicon glyphicon-phone-alt text-success"></span>
                <b>0000</b><br />
                <kbd style="background-color: #1f3b4b;">Организация</kbd> 2019 - @DateTime.Now.Year
            </small>
        </div>
    </div>
</body>
</html>

ERPSolutions_EF/Views/Shared/_ApproveTicketList.cshtml
@model IEnumerable<ERPSolutions_EF.Models.Ticket>

@if (Model.Count() > 0)
{
    <table class="table table-condensed" style="font-size: 9pt;">
        <tr>
            <th><label>Класс</label></th>
            <th><label>Действие</label></th>
            <th><label>Ресурс</label></th>
            <th><label>Создано</label></th>
            <th><label>Решение</label></th>
            <th><label>Описание</label></th>
            <th><label>Тестировщик</label></th>
            <th><label>Автор</label></th>
            <th><label>Согласующий</label></th>
            <th><label>Статус</label></th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            var has_instructions = item.Instructions != null ? true : false;
            var has_fullDesc = item.FullDesc != null ? true : false;
            var has_comments = item.ApproverComments.Count > 0 || item.PerformerComments.Count > 0 ? true : false;
            <tr class="bg-info">
                <td style="font-weight: bold;">
                    <kbd class="bg-primary" style="font-size: 12pt;">@Html.DisplayFor(modelItem => item.Priority.Literal)</kbd>
                </td>
                <td>@Html.DisplayFor(modelItem => item.Operation.Title)</td>
                <td>@Html.DisplayFor(modelItem => item.Resource.Title)</td>
                <td>@Html.DisplayFor(modelItem => item.Created)</td>
                <td>@Html.DisplayFor(modelItem => item.Solutions)</td>
                <td>@Html.DisplayFor(modelItem => item.Desc)</td>
                <td>@Html.DisplayFor(modelItem => item.Tester.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Author.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Approver.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Status.Title)</td>
                <td>
                    @if (has_fullDesc)
                    {
                        <span fulldesc-id="@item.Id" class="glyphicon glyphicon-book fulldesc-icon text-primary"></span>
                    }
                    @if (has_instructions)
                    {
                        <span instruction-id="@item.Id" class="glyphicon glyphicon-info-sign instructions-icon text-primary"></span>
                    }
                    @if (has_comments)
                    {
                        <span comment-id="@item.Id" class="glyphicon glyphicon-comment comments-icon text-primary"></span>
                    }
                </td>
            </tr>
            if (has_fullDesc)
            {
                <tr id="fulldesc_@item.Id" class="fulldesc-content">
                    <td colspan="11">
                        <div>
                            <div><strong>Подробное описание:</strong></div>
                            <div>@item.FullDesc</div>
                        </div>
                    </td>
                </tr>
            }
            if (has_instructions)
            {
                <tr id="instructions_@item.Id" class="instructions-content">
                    <td colspan="11">
                        <div>
                            <div><strong>Дополнительные инструкции по установке:</strong></div>
                            <div>@item.Instructions</div>
                        </div>
                    </td>
                </tr>
            }
            if (has_comments)
            {
                <tr id="comments_@item.Id" class="comments-content">
                    <td colspan="11">
                        <div>
                            @if (item.ApproverComments.Count > 0)
                            {
                                <div><strong>Комментарии по согласованию:</strong></div>
                                foreach (var comment in item.ApproverComments)
                                {
                                    <div><b class="text-primary">@comment.Text</b> (@comment.Date, @comment.Author.Name)</div>
                                    if (comment.Answer != null)
                                    {
                                        <div><b class="text-success">@comment.Answer</b> (@item.Author.Name)</div>
                                    }
                                }
                            }
                        </div>
                    </td>
                </tr>
            }
            <tr>
                <td colspan="11" class="col-md-12">
                    @{Html.RenderAction("HistoryTicketList", "Approve", new { ticketId = item.Id });}
                </td>
            </tr>
            <tr>
                @using (Html.BeginForm("Process", "Approve", new { ticketId = item.Id }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <td colspan="7">
                        @Html.TextArea("comment", null, 3, 1, new { @class = "form-control", style = "margin: 0.2em;", placeholder = "Ваш комментарий..." })
                    </td>
                    <td colspan="4">
                        <input type="submit" value="Согласовать" name="approve" class="form-control btn btn-default input-sm" style="margin: 0.2em;" />
                        <input type="submit" value="Отклонить" name="disapprove" class="form-control btn btn-default input-sm" style="margin: 0.2em;" />
                    </td>
                }
            </tr>
        }
    </table>
}

ERPSolutions_EF/Views/Shared/_AssignTicketList.cshtml
@model IEnumerable<ERPSolutions_EF.Models.Ticket>

@if (Model.Count() > 0)
{
    <table class="table table-condensed" style="font-size: 9pt;">
        <tr>
            <th><label>Класс</label></th>
            <th><label>Действие</label></th>
            <th><label>Ресурс</label></th>
            <th><label>Создано</label></th>
            <th><label>Решение</label></th>
            <th><label>Описание</label></th>
            <th><label>Тестировщик</label></th>
            <th><label>Автор</label></th>
            <th><label>Согласующий</label></th>
            <th><label>Исполнитель</label></th>
            <th><label>Статус</label></th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            var has_instructions = item.Instructions != null ? true : false;
            var has_fullDesc = item.FullDesc != null ? true : false;
            var has_comments = item.ApproverComments.Count > 0 || item.PerformerComments.Count > 0 ? true : false;
            <tr>
                <td style="font-weight: bold;">
                    <kbd class="bg-primary" style="font-size: 12pt;">@Html.DisplayFor(modelItem => item.Priority.Literal)</kbd>
                </td>
                <td>@Html.DisplayFor(modelItem => item.Operation.Title)</td>
                <td>@Html.DisplayFor(modelItem => item.Resource.Title)</td>
                <td>@Html.DisplayFor(modelItem => item.Created)</td>
                <td>@Html.DisplayFor(modelItem => item.Solutions)</td>
                <td>@Html.DisplayFor(modelItem => item.Desc)</td>
                <td>@Html.DisplayFor(modelItem => item.Tester.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Author.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Approver.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Performer.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Status.Title)</td>
                <td>
                    @if (has_fullDesc)
                    {
                        <span fulldesc-id="@item.Id" class="glyphicon glyphicon-book fulldesc-icon text-primary"></span>
                    }
                    @if (has_instructions)
                    {
                        <span instruction-id="@item.Id" class="glyphicon glyphicon-info-sign instructions-icon text-primary"></span>
                    }
                    @if (has_comments)
                    {
                        <span comment-id="@item.Id" class="glyphicon glyphicon-comment comments-icon text-primary"></span>
                    }
                </td>
            </tr>
            if (has_fullDesc)
            {
                <tr id="fulldesc_@item.Id" class="fulldesc-content">
                    <td colspan="12">
                        <div>
                            <div><strong>Подробное описание:</strong></div>
                            <div>@item.FullDesc</div>
                        </div>
                    </td>
                </tr>
            }
            if (has_instructions)
            {
                <tr id="instructions_@item.Id" class="instructions-content">
                    <td colspan="12">
                        <div>
                            <div><strong>Дополнительные инструкции по установке:</strong></div>
                            <div>@item.Instructions</div>
                        </div>
                    </td>
                </tr>
            }
            if (has_comments)
            {
                <tr id="comments_@item.Id" class="comments-content">
                    <td colspan="12">
                        <div>
                            @if (item.ApproverComments.Count > 0)
                            {
                                <div><strong>Комментарии по согласованию:</strong></div>
                                foreach (var comment in item.ApproverComments)
                                {
                                    <div><b class="text-primary">@comment.Text</b> (@comment.Date, @comment.Author.Name)</div>
                                    if (comment.Answer != null)
                                    {
                                        <div><b class="text-success">@comment.Answer</b> (@item.Author.Name)</div>
                                    }
                                }
                            }
                        </div>
                    </td>
                </tr>
            }
            <tr>
                @using (Html.BeginForm("Assign", "Approve", new { ticketId = item.Id }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <td colspan="5"></td>
                    <td colspan="3">
                        @if (item.Performers.Count() == 0)
                        {
                            <h5 class="text-danger">Исполнитель не задан в настройках</h5>
                        }
                        else
                        {
                            @Html.DropDownList(
                                "performerId",
                                new SelectList(item.Performers, "Id", "Name", item.PerformerId),
                                new { @class = "form-control input-sm", style = "margin: 0.2em;" })
                        }
                    </td>
                    <td colspan="4">
                        <input type="submit" value="Назначить" class="form-control btn btn-default input-sm" style="margin: 0.2em;" />
                    </td>
                }
            </tr>
        }
    </table>
}

ERPSolutions_EF/Views/Shared/_DefaultTicketList.cshtml
@model IEnumerable<ERPSolutions_EF.Models.Ticket>

@if (Model != null && Model.Count() > 0)
{
    <table class="table table-condensed table-hover" style="font-size: 9pt;">
        <tr>
            <th><label>Класс</label></th>
            <th><label>Действие</label></th>
            <th><label>Ресурс</label></th>
            <th><label>Создано</label></th>
            <th><label>Решение</label></th>
            <th><label>Описание</label></th>
            <th><label>Тестировщик</label></th>
            <th><label>Автор</label></th>
            <th><label>Согласовано</label></th>
            <th><label>Согласующий</label></th>
            <th><label>Исполнено</label></th>
            <th><label>Исполнитель</label></th>
            <th><label>Статус</label></th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            var has_instructions = item.Instructions != null ? true : false;
            var has_fullDesc = item.FullDesc != null ? true : false;
            var has_comments = item.ApproverComments.Count > 0 || item.PerformerComments.Count > 0 ? true : false;
            <tr>
                <td style="font-weight: bold;">
                    <kbd class="bg-primary" style="font-size: 12pt;">@Html.DisplayFor(modelItem => item.Priority.Literal)</kbd>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Operation.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Resource.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Solutions)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Desc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tester.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Approved)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Approver.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Performed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Performer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status.Title)
                </td>
                <td>
                    @if (has_fullDesc)
                    {
                        <span fulldesc-id="@item.Id" class="glyphicon glyphicon-book fulldesc-icon text-primary"></span>
                    }
                    @if (has_instructions)
                    {
                        <span instruction-id="@item.Id" class="glyphicon glyphicon-info-sign instructions-icon text-primary"></span>
                    }
                    @if (has_comments)
                    {
                        <span comment-id="@item.Id" class="glyphicon glyphicon-comment comments-icon text-primary"></span>
                    }
                </td>
            </tr>
            if (has_fullDesc)
            {
                <tr id="fulldesc_@item.Id" class="fulldesc-content">
                    <td colspan="14">
                        <div>
                            <div><strong>Подробное описание:</strong></div>
                            <div>@item.FullDesc</div>
                        </div>
                    </td>
                </tr>
            }
            if (has_instructions)
            {
                <tr id="instructions_@item.Id" class="instructions-content">
                    <td colspan="14">
                        <div>
                            <div><strong>Дополнительные инструкции по установке:</strong></div>
                            <div>@item.Instructions</div>
                        </div>
                    </td>
                </tr>
            }
            if (has_comments)
            {
                <tr id="comments_@item.Id" class="comments-content">
                    <td colspan="14">
                        <div>
                            @if (item.ApproverComments.Count > 0)
                            {
                                <div><strong>Комментарии по согласованию:</strong></div>
                                foreach (var comment in item.ApproverComments)
                                {
                                    <div><b class="text-primary">@comment.Text</b> (@comment.Date, @comment.Author.Name)</div>
                                    if (comment.Answer != null)
                                    {
                                        <div><b class="text-success">@comment.Answer</b> (@item.Author.Name)</div>
                                    }
                                }
                            }
                            @if (item.PerformerComments.Count > 0)
                            {
                                <div><strong>Комментарии по исполнению:</strong></div>
                                foreach (var comment in item.PerformerComments)
                                {
                                    <div><b class="text-primary">@comment.Text</b> (@comment.Date, @comment.Author.Name)</div>
                                    if (comment.Answer != null)
                                    {
                                        <div><b class="text-success">@comment.Answer</b> (@item.Author.Name)</div>
                                    }
                                }
                            }
                        </div>
                    </td>
                </tr>
            }
        }
    </table>
}

ERPSolutions_EF/Views/Shared/_PerformTicketList.cshtml
@model IEnumerable<ERPSolutions_EF.Models.Ticket>

@if (Model != null && Model.Count() > 0)
{
    <table class="table table-condensed" style="font-size: 9pt;">
        <tr>
            <th><label>Класс</label></th>
            <th><label>Действие</label></th>
            <th><label>Ресурс</label></th>
            <th><label>Создано</label></th>
            <th><label>Решение</label></th>
            <th><label>Описание</label></th>
            <th><label>Тестировщик</label></th>
            <th><label>Автор</label></th>
            <th><label>Согласовано</label></th>
            <th><label>Согласующий</label></th>
            <th><label>Исполнено</label></th>
            <th><label>Исполнитель</label></th>
            <th><label>Статус</label></th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            var has_instructions = item.Instructions != null ? true : false;
            var has_fullDesc = item.FullDesc != null ? true : false;
            var has_comments = item.ApproverComments.Count > 0 || item.PerformerComments.Count > 0 ? true : false;
            <tr>
                <td style="font-weight: bold;">
                    <kbd class="bg-primary" style="font-size: 12pt;">@Html.DisplayFor(modelItem => item.Priority.Literal)</kbd>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Operation.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Resource.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Solutions)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Desc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tester.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Approved)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Approver.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Performed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Performer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status.Title)
                </td>
                <td>
                    @if (has_fullDesc)
                    {
                        <span fulldesc-id="@item.Id" class="glyphicon glyphicon-book fulldesc-icon text-primary"></span>
                    }
                    @if (has_instructions)
                    {
                        <span instruction-id="@item.Id" class="glyphicon glyphicon-info-sign instructions-icon text-primary"></span>
                    }
                    @if (has_comments)
                    {
                        <span comment-id="@item.Id" class="glyphicon glyphicon-comment comments-icon text-primary"></span>
                    }
                </td>
            </tr>
            if (has_fullDesc)
            {
                <tr id="fulldesc_@item.Id" class="fulldesc-content">
                    <td colspan="14">
                        <div>
                            <div><strong>Подробное описание:</strong></div>
                            <div>@item.FullDesc</div>
                        </div>
                    </td>
                </tr>
            }
            if (has_instructions)
            {
                <tr id="instructions_@item.Id" class="instructions-content">
                    <td colspan="14">
                        <div>
                            <div><strong>Дополнительные инструкции по установке:</strong></div>
                            <div>@item.Instructions</div>
                        </div>
                    </td>
                </tr>
            }
            if (has_comments)
            {
                <tr id="comments_@item.Id" class="comments-content">
                    <td colspan="14">
                        <div>
                            @if (item.ApproverComments.Count > 0)
                            {
                                <div><strong>Комментарии по согласованию:</strong></div>
                                foreach (var comment in item.ApproverComments)
                                {
                                    <div><b class="text-primary">@comment.Text</b> (@comment.Date, @comment.Author.Name)</div>
                                    if (comment.Answer != null)
                                    {
                                        <div><b class="text-success">@comment.Answer</b> (@item.Author.Name)</div>
                                    }
                                }
                            }
                            @if (item.PerformerComments.Count > 0)
                            {
                                <div><strong>Комментарии по исполнению:</strong></div>
                                foreach (var comment in item.PerformerComments)
                                {
                                    <div><b class="text-primary">@comment.Text</b> (@comment.Date, @comment.Author.Name)</div>
                                    if (comment.Answer != null)
                                    {
                                        <div><b class="text-success">@comment.Answer</b> (@item.Author.Name)</div>
                                    }
                                }
                            }
                        </div>
                    </td>
                </tr>
            }
            <tr>
                @using (Html.BeginForm("Process", "Perform", new { ticketId = item.Id }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    if (item.PerformerId == null)
                    {
                        <td colspan="8">
                            @Html.TextArea("comment", null, 3, 1, new { @class = "form-control", style = "margin: 0.2em;", placeholder = "Ваш комментарий..." })
                        </td>
                        <td colspan="6">
                            <input type="submit" value="Взять в работу" name="assign" class="form-control btn btn-default input-sm" style="margin: 0.2em;" />
                        </td>
                    }
                    else if (item.PerformerId == (int)Session["performerId"])
                    {
                        <td colspan="8">
                            @Html.TextArea("comment", null, 3, 1, new { @class = "form-control", style = "margin: 0.2em;", placeholder = "Ваш комментарий..." })
                        </td>
                        <td colspan="6">
                            <input type="submit" value="Выполнено" name="perform" class="form-control btn btn-default input-sm" style="margin: 0.2em;" />
                            @if (item.StatusId != (int)ERPSolutions_EF.Models.Enums.Statuses.HOLD)
                            {
                                <input type="submit" value="Пауза" name="hold" class="form-control btn btn-default input-sm" style="margin: 0.2em;" />
                            }
                            <input type="submit" value="Отклонить" name="decline" class="form-control btn btn-default input-sm" style="margin: 0.2em;" />
                        </td>
                    }
                }
            </tr>
        }
    </table>
}

ERPSolutions_EF/Views/Shared/_SolutionHistoryList.cshtml
@model IEnumerable<ERPSolutions_EF.Models.Ticket>

@if (Model != null)
{
    <h5 class="text-primary">История заявок по номеру решения: <b>@Model.Count()</b> шт.</h5>

    <table class="table" style="color: gray;">
        <tr>
            <th>Класс</th>
            <th>Действие</th>
            <th>Ресурс</th>
            <th>Решение</th>
            <th>Краткое описание</th>
            <th>Тестировщик</th>
            <th>Создано</th>
            <th>Согласовано</th>
            <th>Выполнено</th>
            <th>Автор</th>
            <th>Согласующий</th>
            <th>Исполнитель</th>
            <th>Статус</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Priority.Literal)</td>
                <td>@Html.DisplayFor(modelItem => item.Operation.Title)</td>
                <td>@Html.DisplayFor(modelItem => item.Resource.Title)</td>
                <td>@Html.DisplayFor(modelItem => item.Solutions)</td>
                <td>@Html.DisplayFor(modelItem => item.Desc)</td>
                <td>@Html.DisplayFor(modelItem => item.Tester.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Created)</td>
                <td>@Html.DisplayFor(modelItem => item.Approved)</td>
                <td>@Html.DisplayFor(modelItem => item.Performed)</td>
                <td>@Html.DisplayFor(modelItem => item.Author.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Approver.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Performer.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Status.Title)</td>
            </tr>
        }
    </table>
}
else
{
    <h5 class="text-danger">История по номеру решения отсутствует</h5>
}